### PR TITLE
import refactoring

### PR DESCRIPTION
**Pull request by josephdviviano**
Happy to clean up the commits here if requested -- I iterated on a few things during development, in particular, I was abusing the `TYPE_CHECKING` flag and had to remove those changes. So while there are a large number of commits the diffs should be straightforward to follow.

In my attempt to understand the dependency structure of this repo (using `pydeps`) I decided to perform a very slight refactoring of just the module imports (I also moved a single function to it's own module). I am sure we can further disentangle the modules of this library (in particular `gfn.containers`), I only handled the low hanging fruit. In particular I'm strict about modules inheriting from the public namespaces of their neighbours.

This was mostly an exercise for me to understand the structure of the codebase and I am happy to re-do it entirely from scratch in a different way. In general the library is really nicely structured, but also quite intricate, so it's hard to come up with a simple refactoring. The most interesting output of the work is likely this image which will at least be of interest to @vict0rsch, and perhaps others

  GFN Codebase Dependencies MindMap

### CODE REVIEW

**Comment by saleml** [comment]
This looks great, thanks for the PR. I'll have a look tomorrow.

**Comment by josephdviviano** [comment]
Closed as this was already merged into `generic-gfn` by https://github.com/saleml/gfn/pull/29

**Comment by josephdviviano** [comment]
Closed as this was already merged into `generic-gfn` by https://github.com/saleml/gfn/pull/29

**Comment by josephdviviano** [comment]
Closed as this was already merged into `generic-gfn` by https://github.com/saleml/gfn/pull/29

**Pull request closed without merging**
